# Generated by Django 3.2.1 on 2022-05-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'На складе'), ('2', 'В заказе'), ('3', 'Продана')], default='1', help_text='На складе', max_length=1),
        ),
    ]
